<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Vote Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="narrow.css">
    <link rel="stylesheet" href="vote.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="container">
      <div class="jumbotron2">
        <h1>VoteApp</h1>
        <h4 class="center">Vote for RED, GREEN, or BLUE on</h4>
        <h2 class="row"><a href="http://ec-vote-app.mybluemix.net">ec-vote-app.mybluemix.net</a></h2>

        <p class="lead">This is a demonstration of serverless web application backend, build on IBM Bluemix </p>
      </div>

      <div class="row">
        <div class="col-md-12"><canvas id="graph" class="inner cover" width="500" height="420"></canvas></div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <p>OpenWhisk monitors a CouchDB table, which is populated with votes generated by the voting website <a href="http://ec-vote-app.mybluemix.net">ec-vote-app.mybluemix.net</a>
            When the table is updated, OpenWhisk invokes code to query the table and aggregate the votes, which are used to update the graph above.</p>
        </div>
      </div>

      <footer class="footer">
        <p>Demo based on <a href="https://medium.com/aws-activate-startup-blog">AWS Startup Collection</a> on <a href="http://medium.com/">Medium</a>.</p>
      </footer>

    </div> <!-- /container -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.1.40.min.js"></script>
    <script src="refresh.js"></script>
  </body>
</html>
